### ISSUE TITLE
Idea: World and Save Command-Line Arguments

### ISSUE THREAD

**Issue by ChristianSilvermoon** [TheXTech/TheXTech#36]
It would be really cool to be able to specify World and Save from the command-line.

A `--world=` argument could be either `--world="Name"` for a world in the usual location, or `--world=./Name` for a world in the current directory... or any other path.

A `--save` argument could take either a 1, 2, or 3... or a path to a file for arguments.

`thextech --world="WorldPath" --save="SavePath" --player1 <c1>`

Could potentially throw an error if the character value is invalid for that Episode. IE an episode that blocks character 3 could cause the game to exit and display a list of valid values. 

This would allow one to easily make shortcuts to start up a particular save and episode to continue, or to use saves that  *aren't* one of the three defaults, to basically easily allow unlimited saves.

Additionally could also skip the title on game over and reload the save, unless `Save & Quit` is used or the credits are reached.

**Comment by Wohlstand** [comment]
what about the ability to point the specific file for the `--save=`, that would be tricky, but is possible :fox_face: :+1:

**Comment by ChristianSilvermoon** [comment]
Pointing to the world map file makes way more sense, yeah ^^

**Comment by ds-sloth** [comment]
Should we include this feature in 1.3.6.1?

It would be reasonably easy to force `SelectWorld` to include an external file passed to the engine and start gameplay with that world, skipping the menu.

Challenges:
* "save file" isn't just a `savx`, it's actually a `savx` plus separate files for timers, fails counter, and (in future) settings. I propose that we limit the command-line argument to save slots only. (Perhaps rename it `--slot`.)
* How do we deal with a case where an external world has the same folder and file names as an in-game world? Should we use the same save files? This could lead to unexpected issues if different versions of the same episode are used.

**Comment by Wohlstand** [comment]
I guess, yes, it's suitable to just have the `--slot x` for the stuff. Also, it's possible to make a kind of the `--slot 0` (default) to run the game with a `/dev/null`-led gamesave. I.e. the temporary gamesave that will not be saved after quitting the game.

**Comment by ChristianSilvermoon** [comment]
> I guess, yes, it's suitable to just have the `--slot x` for the stuff. Also, it's possible to make a kind of the `--slot 0` (default) to run the game with a `/dev/null`-led gamesave. I.e. the temporary gamesave that will not be saved after quitting the game.

Using a null save by default also makes this a great step towards full Episode Testing ^^

Would it also, in theory be possible to specify an arbitrary digit above 3 in this case?

**Comment by Wohlstand** [comment]
> Would it also, in theory be possible to specify an arbitrary digit above 3 in this case?

That will be possible if gamesaves list will be turned into the kind of std-vector, or there will be a separated indicator of the gamesave number that doesn't depends on the built-in list. I.e. store loaded data at one single place, but allow the gamesave slot to have any value, keeping all stuff being written and loaded properly. But, that sounds a work for the future. At first, need to make a very simple thing.

**Comment by Wohlstand** [comment]
> Should we include this feature in 1.3.6.1?

I think, it would be a thing for the 1.3.6.2 if not for 1.3.7, if we want to release 1.3.6.1 as fast as possible.

**Comment by ChristianSilvermoon** [comment]
> > Would it also, in theory be possible to specify an arbitrary digit above 3 in this case?
> 
> That will be possible if gamesaves list will be turned into the kind of std-vector, or there will be a separated indicator of the gamesave number that doesn't depends on the built-in list. I.e. store loaded data at one single place, but allow the gamesave slot to have any value, keeping all stuff being written and loaded properly. But, that sounds a work for the future. At first, need to make a very simple thing.


I wouldn't mind seeing the Save Menu turn into something Page-inated (Left/right to switch pages) and support an arbitrary number of saves were that the case, but that'd be a separate feature/request x3

**Comment by Wohlstand** [comment]
I forgot to tell: To supply a world map to start the world map playing, is NO need to give an extra argument, it's very easy to recognise, do we play a world map or a level. So, no `--world` argument is needed: just a file.

**Comment by ChristianSilvermoon** [comment]
> I forgot to tell: To supply a world map to start the world map playing, is NO need to give an extra argument, it's very easy to recognise, do we play a world map or a level. So, no `--world` argument is needed: just a file.

Ah, that's a fair point :thinking:
It would be kinda redundant, huh?

**Comment by ds-sloth** [comment]
Should be implemented now! @ChristianSilvermoon can you please test? We can adjust the details if that's helpful.

@Wohlstand, please review the following commits before we close the issue: a2f9d2da281b94811d6b20876ea7c9988a48c787 41f2e845b78124e5373c8bab6b51be94ef50a1ec 79d12767f472519ba03adf2e4b1b522130c713ff

**Comment by ChristianSilvermoon** [comment]
The save arguement does appear to work

However, I would say that there's an issue with starting worlds.

If I specify
```
thextech --save-slot 1 "world.wld"
```

The game will throw an error about being unable to find it, despite it being in the present working directory, however, including `./` to signify "current directory" does work.

I think having the present working directory be implicit when the path does not begin with a `/` or `C:\` (or other drive letter) in Windows' case makes sense, and would make it consistent with starting level files, which already treat `./` as implicit

**Comment by ChristianSilvermoon** [comment]
Update: It's also possible to select invalid characters for the episode via
```
thextech -1 c3 ./world.wld
```

This should possibly print a warning or something. In Super Mario Bros. 0 for instance, this causes death during the intro cutscene due to differing character physics

**Comment by ds-sloth** [comment]
> The game will throw an error about being unable to find it, despite it being in the present working directory, however, including ./ to signify "current directory" does work.

I see, that is probably because of some problem with the way the episode folder and world file are split. I'll take a look now, thanks.

> It's also possible to select invalid characters.

Better to print a warning or use the available characters?

**Comment by ds-sloth** [comment]
Please give this a try. I believe I fixed both issues (and solved the second by finding an available character, not by printing a warning)

**Comment by ChristianSilvermoon** [comment]
Still have a few things to test, but I've found that curiously the following occur

```bash
thextech --save-slot 1 world.wld
# Save does not load

thextech --save-slot 1 ./world.wld
# Save does not load

thextech --save-slot 1 "$PWD/world.wld"
# Save DOES load
```
This is a strange behavior :thinking:

**Comment by ChristianSilvermoon** [comment]
And finished testing that... character *does* fall back to a supported character...

Would there be any way to instead hook into the Add/Drop Players interface for character selection in this particular situation instead? It might be a little more user friendly.

**Comment by ds-sloth** [comment]
Thanks for letting me know about the confused save behavior. I'll take an absolute path; that should fix the issue.

> Would there be any way to instead hook into the Add/Drop Players interface for character selection in this particular situation instead? It might be a little more user friendly.

That'd be a bit tricky, given the sequence of when things are processed. I suppose it might be possible to just show the menu's connection screen here, but I don't know whether most users would prefer that.

**Comment by ChristianSilvermoon** [comment]
> Thanks for letting me know about the confused save behavior. I'll take an absolute path; that should fix the issue.
> 
> > Would there be any way to instead hook into the Add/Drop Players interface for character selection in this particular situation instead? It might be a little more user friendly.
> 
> That'd be a bit tricky, given the sequence of when things are processed. I suppose it might be possible to just show the menu's connection screen here, but I don't know whether most users would prefer that.

My reasoning is that to me it'd be more clear to the player that they need to choose a different character, rather than them specifying they want character 3 and being put in as character 1 with no understanding as to why or what characters are valid. This way they get to pick and the game shows them what is and isn't an option for that world.

**Comment by ds-sloth** [comment]
That's good reasoning. The only way to do this without fully rewriting the reconnection screen would be to start up the menu screen, and likely allow the player to escape to the rest of the menu. Do you think that is worth it?

**Comment by ChristianSilvermoon** [comment]
> That's good reasoning. The only way to do this without fully rewriting the reconnection screen would be to start up the menu screen, and likely allow the player to escape to the rest of the menu. Do you think that is worth it?

:thinking: I'd say maybe so, assuming it still jumps straight to the game with a valid character

Hmm... what would happen if the episode were outside the directory the game normally looks in that case though? If you left that menu, would it become inaccessible?

**Comment by 0lhi** [comment]
I don't know the full context, but from what I just caught, wouldn't it be possible to have the command line say that this character isn't allowed, and have an `-f` / `--force` option that will pick that character anyway?

**Comment by ds-sloth** [comment]
> Hmm... what would happen if the episode were outside the directory the game normally looks in that case though? If you left that menu, would it become inaccessible?

That is possible to work around if this is the UI we like best.

> have a force option

I'd rather not add even more command line arguments.

**Comment by ChristianSilvermoon** [comment]
> > @0lhi  
> > have a force option
> 
> @ds-sloth 
> I'd rather not add even more command line arguments.

What if instead of adding a new option, we extended the existing one.
If we made it possible to do this:
```
# Current behavior
thextech -1 c2

# Force behavior
thextech -1 C2
```
instead?

This would avoid adding a new (and possibly vague option) and give us a way to force the character from CLI arguments, which admittedly could be useful for episode testing when it comes to episodes that normally have restrictions

**Comment by 0lhi** [comment]
Maybe f2 would be more appropriate than C2? I do like the idea.

**Comment by ChristianSilvermoon** [comment]
> Maybe f2 would be more appropriate than C2? I do like the idea.

Using "f" for force may be more ambiguous in meaning than "C" for "Character, but with higher emphasis"

There are some programs which us capital letters as arguments to emphasize intensity.

**Comment by ChristianSilvermoon** [comment]
Is this not implemented at this point?

**Comment by Wohlstand** [comment]
Ye, sounds like this thing is already implemented, I should close this. Thanks for a note!
